#!/usr/bin/env python3
# PS5: files built into the title, for the frontend to write out at its start.
#
# FTP could not add RPCS3's overlay images (bin/Icons/ui) to the title's rpcs3/
# folder, which the title made (fs_move_failed, on my console); the frontend,
# which may write there, does instead (ps5_frontend.cpp, install_embedded_files).
#
# Usage: embed_files.py <out.cpp> <base directory> <files...>
# Writes ps5_embedded_files[] and ps5_embedded_file_count, each file named by
# its path below the base directory.
import os
import sys


def main():
    out, base, files = sys.argv[1], sys.argv[2], sys.argv[3:]
    lines = ["// Generated by rpcs3/ps5/embed_files.py: do not edit", "",
             "#include \"ps5_embedded_files.h\"", ""]
    entries = []
    for i, path in enumerate(sorted(files)):
        data = open(path, "rb").read()
        name = os.path.relpath(path, base).replace(os.sep, "/")
        lines.append(f"static const unsigned char s_file_{i}[] = {{")
        for at in range(0, len(data), 24):
            lines.append("\t" + ", ".join(str(b) for b in data[at:at + 24]) + ",")
        lines.append("};")
        entries.append(f"\t{{\"{name}\", s_file_{i}, sizeof(s_file_{i})}},")
    lines += ["", "const ps5_embedded_file ps5_embedded_files[] = {"] + entries + ["};", "",
              f"const unsigned ps5_embedded_file_count = {len(entries)};", ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))


main()
