#!/usr/bin/env python3
# PS5: RPCS3's English strings for its native dialogs, without Qt.
#
# The desktop's strings are in rpcs3qt/localized_emu.h, a switch over
# localized_string_id returning tr("English", "context"). The frontend had
# none, and the dialogs drew their button prompts with no words (the save data
# list's X and O, on my console). This reads the English out of that switch, so
# the console's strings follow RPCS3's own.
#
# Usage: localized_strings.py <localized_emu.h> <out.cpp>
# Writes ps5_localized_string(id): the English, with %0 where an argument
# goes, or nullptr for an id it does not know.
import re
import sys

CASE = re.compile(r'case\s+localized_string_id::(\w+)\s*:\s*return\s+(?:tr\(\s*)?("(?:[^"\\]|\\.)*")')


def main():
    header, out = sys.argv[1], sys.argv[2]
    text = open(header, encoding="utf-8").read()
    cases = CASE.findall(text)
    lines = ["// Generated by rpcs3/ps5/localized_strings.py from rpcs3qt/localized_emu.h: do not edit",
             "",
             "#include \"stdafx.h\"",
             "#include \"Emu/localized_string_id.h\"",
             "",
             "const char* ps5_localized_string(localized_string_id id)",
             "{",
             "\tswitch (id)",
             "\t{"]
    for name, literal in cases:
        lines.append(f"\tcase localized_string_id::{name}: return {literal};")
    lines += ["\tdefault: return nullptr;", "\t}", "}", ""]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"localized_strings.py: {len(cases)} strings")


main()
